version: "3.9"
services:
    minecraft:
        image: hapewe/spigot:1.18
        container_name: minecraft
        hostname: minecraft
        volumes:
            - type: volume
              source: minecraft_data
              target: /mnt/minecraft:rw
        ports:
            - 25565:25565
        environment:
            HEAP: "2G"
        command: [";", "sh", "-c", "java -Xmx${HEAP} -Xms${HEAP} -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:+DisableExplicitGC -XX:TargetSurvivorRatio=90 -XX:G1NewSizePercent=50 -XX:G1MaxNewSizePercent=80 -XX:InitiatingHeapOccupancyPercent=10 -XX:G1MixedGCLiveThresholdPercent=50 -XX:+AlwaysPreTouch -Dcom.mojang.eula.agree=true -Dfile.encoding=UTF-8 -jar /opt/minecraft/spigot.jar nogui"]
        networks:
            compose-minecraft:
                ipv4_address: 10.1.2.10
        restart: on-failure
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        volumes:
            - ./prometheus:/prometheus-data
        command:
            - "--config.file=/prometheus-data/prometheus.yml"
        restart: on-failure
        networks:
            compose-minecraft:
                ipv4_address: 10.1.2.2
    node_exporter:
        image: quay.io/prometheus/node-exporter
        container_name: node-exporter
        volumes:
            - '/:/host:ro,rslave'
        networks:
            compose-minecraft:
                ipv4_address: 10.1.2.3
        command:
            - 'path.rootfs=/host'
        network_mode: host
        restart: unless-stopped
    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        restart: on-failure
        networks:
            compose-minecraft:
volumes:
    minecraft_data:
networks:
    compose-minecraft:
        ipam:
            driver: default
            config:
                - subnet: 10.1.2.0/24
