version: "3.9"
services:
    minecraft:
        image: hapewe/spigot:1.18
        container_name: minecraft
        hostname: minecraft
        volumes:
            - ./spigot:/opt/minecraft
        ports:
            - 25565:25565
              #- 9225:9225
        environment:
            HEAP: '4G'
        networks:
            compose-minecraft:
                ipv4_address: 10.1.2.10
        restart: unless-stopped
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        hostname: prometheus
        volumes:
            - ./prometheus:/prometheus-data
              #ports:
              #    - 9090:9090
        command:
            - "--config.file=/prometheus-data/prometheus.yml"
        restart: always
        networks:
            compose-minecraft:
                ipv4_address: 10.1.2.2
    node_exporter:
        image: quay.io/prometheus/node-exporter
        container_name: node-exporter
        #       ports:
        #   - 9101:9101
        volumes:
            #   - /proc:/host/proc
            #- /sys:/host/sys
            #- /:rootfs
            - '/:/host:ro,rslave'
        networks:
            compose-minecraft:
                ipv4_address: 10.1.2.3
        command:
            - 'path.rootfs=/host'
        network_mode: host
        restart: unless-stopped
    grafana:
        image: grafana/grafana
        container_name: grafana
        hostname: grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        networks:
            compose-minecraft:
networks:
    compose-minecraft:
        ipam:
            driver: default
            config:
                - subnet: 10.1.2.0/24
#    cadvisor:
#       image: google/cadvisor:latest
#       container_name: cadvisor
#       host_name: cadvisor
#       volumes:
#           - /:/rootfs:ro
#            - /var/run:/var/run:rw
#           - /sys:/sys:ro
#           - /var/lib/docker/:/var/lib/docker:ro
#           - /dev/disk/:/dev/disk:ro
#        ports:
#            - 8080:8080
#        restart: always
